# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pioadmin < Formula
  desc ""
  homepage "https://github.com/pilvio-com/pioadmin"
  version "0.1.6-rc2"

  on_macos do
    url "https://github.com/pilvio-com/pioadmin/releases/download/v0.1.6-rc2/pioadmin_0.1.6-rc2_darwin_all.tar.gz"
    sha256 "9bfb74faf2b215eb5a19cd5a91846fcc8b29ff21472e5ef7d0a00b03073dcadf"

    def install
      bin.install "pioadmin"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pilvio-com/pioadmin/releases/download/v0.1.6-rc2/pioadmin_0.1.6-rc2_linux_arm64.tar.gz"
      sha256 "35062e845cd3c3eadf589e1bc1168402117a33974bb48d5985136e2372b6d36c"

      def install
        bin.install "pioadmin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pilvio-com/pioadmin/releases/download/v0.1.6-rc2/pioadmin_0.1.6-rc2_linux_amd64.tar.gz"
      sha256 "f4c1421365e9bf0f622201a45e04027ddf2e37e54cb477e8f7a3b26dcd61e676"

      def install
        bin.install "pioadmin"
      end
    end
  end
end
