# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pioadmin < Formula
  desc ""
  homepage "https://github.com/pilvio-com/pioadmin"
  version "0.1.5-rc7"

  on_macos do
    url "https://github.com/pilvio-com/pioadmin/releases/download/v0.1.5-rc7/pioadmin_0.1.5-rc7_darwin_all.tar.gz"
    sha256 "8894dc8b1e8ceefc38d17dcc014090526db3deb8c101c0f54b717ef1bc05db56"

    def install
      bin.install "pioadmin"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pilvio-com/pioadmin/releases/download/v0.1.5-rc7/pioadmin_0.1.5-rc7_linux_arm64.tar.gz"
      sha256 "1630d4179c21997edc45794d9fd2972d70ea17bcb3e34be2e596042c6683ccac"

      def install
        bin.install "pioadmin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pilvio-com/pioadmin/releases/download/v0.1.5-rc7/pioadmin_0.1.5-rc7_linux_amd64.tar.gz"
      sha256 "c7ecba5429724489abeeebbc6426079a194e1bf218602862e7566dfddfedffa5"

      def install
        bin.install "pioadmin"
      end
    end
  end
end
