# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pioctl < Formula
  desc ""
  homepage "https://github.com/pilvio-com/pioctl"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pilvio-com/pioctl/releases/download/v0.3.0/pioctl_0.3.0_darwin_arm64.tar.gz"
      sha256 "c2a3c45bf274edccec57ea29f237725bb2de922b5f090532a0b11280271bb632"

      def install
        bin.install "pioctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pilvio-com/pioctl/releases/download/v0.3.0/pioctl_0.3.0_darwin_amd64.tar.gz"
      sha256 "72e187e94003f68634e755d9713c1392031abac878a3dad1b8f1d741cb23ac25"

      def install
        bin.install "pioctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pilvio-com/pioctl/releases/download/v0.3.0/pioctl_0.3.0_linux_arm64.tar.gz"
      sha256 "43a52ce0fdbb30a514ea273f52c4edf8d942befc87dd4a38545e5a61c58d712a"

      def install
        bin.install "pioctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pilvio-com/pioctl/releases/download/v0.3.0/pioctl_0.3.0_linux_amd64.tar.gz"
      sha256 "462bd2bdd5ae0615a716288a92d39afe78cfb34c3fb22c4a24749c0039e86c37"

      def install
        bin.install "pioctl"
      end
    end
  end
end
